### ISSUE TITLE
LSP server crashes when hovering on constants

### ISSUE THREAD

**Issue by tirix** [tirix/metamath-vspa#6]
@glacode mentioned in issue #2 :

> I'm getting an error when I hover on a constant; and the LSP server crashes/restarts:
```
thread 'main' panicked at 'called Option::unwrap() on a None value', //.cargo/git/checkouts/metamath-knife-c0afdf58ccf11b37/7954d40/src/grammar.rs:462:80
stack backtrace:
0: rust_begin_unwind
at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
1: core::panicking::panic_fmt
at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
2: core::panicking::panic
at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
3: metamath_knife::grammar::Grammar::too_short
4: metamath_knife::grammar::Grammar::parse_formula
5: mm_lsp_server::definition::find_statement
6: mm_lsp_server::hover::hover
7: mm_lsp_server::server::Server::run
8: mm_lsp_server::main
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
[Info - 12:30:40 AM] Connection to server got closed. Server will restart.
[Error - 12:30:40 AM] Request textDocument/hover failed.
```

**Comment by tirix** [comment]
This is due to an issue in `metamath-knife`'s diagnostics, which is corrected in [v0.3.2](https://github.com/david-a-wheeler/metamath-knife/releases/tag/v0.3.2), PR [#75](https://github.com/david-a-wheeler/metamath-knife/pull/75).

The LSP servers tries to build a formula with the single math token in order to resolve its declaration. This failed in the case of a constant which is not a full formula but only a part of a formula (like for an opening parens), with a panic. The fix avoids panicking in that case.

It is still not possible to get a reference to a syntax axiom in that case, but the LSP server can fall back to showing the corresponding `$c` constant declaration.

**Comment by tirix** [comment]
@glacode this fix works for me, I'll close this issue when you confirm it also works for you!

**Comment by glacode** [comment]
I confirm that it works, now

**Comment by tirix** [comment]
Thanks, closing!
